#!/bin/bash

# ============================================
# BACKEND STARTUP INSTRUCTIONS
# ============================================

echo "=================================="
echo "STEP-BY-STEP BACKEND STARTUP"
echo "=================================="
echo ""
echo "1. Open a NEW Terminal Window"
echo ""
echo "2. Copy and paste this command:"
echo ""
echo "   cd \"/Users/renuka.patil02/Library/CloudStorage/OneDrive-UKG/Desktop/comp/StudentManagementSystem-React-Java/backend-java\" && ./apache-maven-3.9.6/bin/mvn spring-boot:run"
echo ""
echo "3. Wait for this message:"
echo "   'Started StudentManagementApplication in X.XXX seconds'"
echo ""
echo "4. The backend will be available at:"
echo "   http://localhost:8081/api"
echo ""
echo "5. Test it by opening in browser:"
echo "   http://localhost:8081/api/students"
echo ""
echo "=================================="
echo "WHAT WAS FIXED:"
echo "=================================="
echo ""
echo "✅ Phone validation now accepts numbers starting with 0"
echo "✅ Pattern: ^[+]?[0-9]{10,15}$"
echo "✅ Allows: 07756969570, +917756969570, etc."
echo "✅ Fixed in both Student and Inquiry models"
echo ""
echo "✅ Frontend form now sends correct fields:"
echo "   - firstName, lastName, email, phone"
echo "   - dateOfBirth, gender, course, status, address"
echo ""
echo "✅ API URL updated to port 8081"
echo ""
echo "=================================="
echo "TO TEST ADD STUDENT:"
echo "=================================="
echo ""
echo "1. Go to http://localhost:3000/add-student"
echo "2. Fill in the form:"
echo "   - First Name: Test"
echo "   - Last Name: User"
echo "   - Email: test@example.com"
echo "   - Phone: 07756969570 (now works!)"
echo "   - Date of Birth: 2000-01-01"
echo "   - Gender: Male"
echo "   - Course: Computer Science"
echo "   - Address: Your address"
echo "3. Click 'Add Student'"
echo "4. Should see success message!"
echo ""
echo "=================================="

